---
# Vars: htpasswd_user
# Passwords: htpasswd_pass

- name: Include vars
  include_vars:
    file: vars/passwords/passwords.yml

- name: Install htpasswd dependencies
  apt:
    name: python-passlib
    state: installed

- name: Create basic auth password
  htpasswd:
    path: /etc/apache2/.htpasswd
    name: "{{ htpasswd_user }}"
    password: "{{ htpasswd_pass }}"
    owner: root
    group: root
    mode: 0644

- name: Restart apache2
  service:
    name: apache2
    state: restarted
