---
vsftpd_conf: |
  listen=YES
  anonymous_enable=NO
  local_enable=YES
  write_enable=YES
  local_umask=022
  xferlog_enable=YES
  connect_from_port_20=YES
  chroot_local_user=YES
  chroot_list_enable=YES
  chroot_list_file=/etc/vsftpd.chroot_list
  secure_chroot_dir=/var/run/vsftpd/empty
  pasv_enable=YES
  pasv_max_port=10100
  pasv_min_port=10090
  # Sometimes server returns wrong address, specify its public IP here
  pasv_address=54.175.76.152
